### ISSUE TITLE
Aptos NFT bridge support

### ISSUE THREAD

**Issue by kev1n-peters** [wormhole-foundation/example-token-bridge-ui#44]

**Comment by kev1n-peters** [comment]
https://github.com/XLabs/portal-bridge-ui/pull/36

**Comment by aadam-10** [comment]
waiting for the execution of https://governance.aptosfoundation.org/proposal/4

**Comment by aadam-10** [comment]
https://github.com/XLabs/portal-bridge-ui/pull/36
